### ISSUE TITLE
Razor view msgctxt incorrect 

### ISSUE THREAD

**Issue by jooni91** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#59]
The context for strings on Razor views is in an incorrect format.

Currently:
`msgctxt "Module\\Views\\MyPart.Edit"`

Expected:
`msgctxt "Module.Views.MyPart.Edit"`

Am I doing something wrong?

**Comment by hishamco** [comment]
Please steps to reproduce

**Comment by jooni91** [comment]
Using the `PoExtractor` tool: 
1. Add a localizable string to a Razor view, e.g. `@T["My string"]`.
2. Run `extractpo inputpath outputpath` against the solution/project that the Razor view is in.
3. See the results in the output file.

Not sure, but #54 might have fixed this problem. But it seems that this fix was not yet published on NuGet. The fix was merged into master on `9/29/2021` while the latest version on NuGet was published on `5/20/2021`.

**Comment by hishamco** [comment]
I will publish a new package in the upcoming days, so I will close this issue for now. Feel free to reopen if the issue still exist
