### ISSUE TITLE
.NET 6 Release

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#63]
I'm not in a rush @hishamco but I figured I should make an issue for releasing a new version of the extractor tool that uses .NET 6.

Thanks for taking over the repo.

**Comment by hishamco** [comment]
We 're on rush ;), I already upgraded the packages in https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/commit/2061d1d11009eea214342b43205b86954c012f7c

There's an issue reported by @skrypt, we will check if we can fix it, then release or release after the fix

I will keep you updated

**Comment by hishamco** [comment]
@rjpowers10 https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.0-preview will be available soon, your feedback are welcome

**Comment by hishamco** [comment]
https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/releases/tag/v1.0.0-preview

**Comment by hishamco** [comment]
https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/releases/tag/v1.0.0

FYI @rjpowers10 @agriffard
