### ISSUE TITLE
Merge PoExtractor & PoExtractor.OrchardCore into a single tool

### ISSUE THREAD

**Issue by hishamco** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#64]
Now we have two tools which do the same things except `PoExtractor.OrchardCore` extend the first one by supporting liquid, while the intend of `PoExtractor` to extract translatable strings in Orchard Core, single tool is enough. We might extend this tool by having options to skip certain template

/cc @Skrypt

**Comment by lukaskabrt** [comment]
Just some notes from the history ...
* There used to be `--liquid` switch, but it was removed in #34 
* Original idea behind two separate tools was not to force other consumers of the tool to take dependency on Orchard Core

**Comment by hishamco** [comment]
Thanks for your input @lukaskabrt

> Original idea behind two separate tools was not to force other consumers of the tool to take dependency on Orchard Core

I expect that but while we are using the OC localization identifier conventions it doesn't make sense
