### ISSUE TITLE
Wrong message context while extract localizer string in Razor pages

### ISSUE THREAD

**Issue by dung691** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#67]
While extract po using command:

`extractpo ..\WebApplication1\WebApplication1 .\Output` 

The output of po file wrong msgctxt for Razor page Index

instead of msgctxt is `WebApplication1.Pages.Index`. it output msgctxt `Pages.Index`.

see attached project
[WebApplication1.zip](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/files/10230593/WebApplication1.zip)

**Comment by hishamco** [comment]
Are you using the latest bits? If Yes we need to fix it before release `1.0.0`

**Comment by hishamco** [comment]
@rjpowers10 did you come across this issue with the latest bits?

**Comment by hishamco** [comment]
There was unexpected but, I will fix it soon

**Comment by hishamco** [comment]
Fixed in https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/commit/441dffb51f77fc7b9520e82a1aa8c03860e50bd6
