### ISSUE TITLE
why are the extracted files from tool .pot and not .po ?

### ISSUE THREAD

**Issue by giannik** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#71]
Why is the extnesion of the files generated as .pot ?
I mean when i copy them to the Localization folder in my web project shoud'nt they be renamed to  *.po extension ?

**Comment by hishamco** [comment]
Please refer to this article first https://www.icanlocalize.com/site/tutorials/how-to-translate-with-gettext-po-and-pot-files

**Comment by giannik** [comment]
Thank you. Got it.
