### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by vukasinpetrovic** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#75]
I just tried the tool, but it gives no output, output folder is empty. Version installed is 1.0.1.
This is the command called:

/Users/apple/.dotnet/tools/extractpo '/Users/apple/Documents/Projects/Web/Skenit/Skenit.API/Controllers/V1' '/Users/apple/Documents/Projects/Web/Skenit/Skenit.API/generated_po'

Path to extractpo is done manually as dotnet command would not find it after installing globally for some reason.
If I miss the path, ie. input path is wrong, tool gives me output of instructions how to use it.

**Comment by hishamco** [comment]
Hi, @vukasinpetrovic I need to know if the issue is in your path and if you want the tool gives you the output instructions on how to use it. Or is there something else?

**Comment by hishamco** [comment]
The tool already shows the usage, have a look to the following snippet

https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/blob/354190e48f2d6edbce07b8e8e015d4c1c6a096e0/src/OrchardCoreContrib.PoExtractor/Program.cs#L171-L186

**Comment by vukasinpetrovic** [comment]
@hishamco If I set path that does not exist for input path argument, tool prints out usage text. See image below. 
![image](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/assets/23005422/1a62a655-84c2-42ef-ada9-679185b309d9)

If I add correct paths as the arguments, command looks like it executes right, but it generates no output, folder is empty.
![image](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/assets/23005422/5b7e2f56-f160-400c-8f8a-8081b2f787c9)

**Comment by hishamco** [comment]
> @hishamco Tool can extract string from Controllers (c# classes), or just razor views?

It should extract everything, FYI you can select the language & template to help the tool what should be extracted

**Comment by hishamco** [comment]
> "Controllers"

Try to point to your solution path, not the `Controllers` folder, also no need to provide the tool path, just use `extractpo`

**Comment by vukasinpetrovic** [comment]
@hishamco Ok, it had to be the root of the project and most importantly localizer has to be named "S" inside the code. Why is that mandatory as when I use Orchardcore I can name my variable whatever I want and it worked fine?

**Comment by vukasinpetrovic** [comment]
That option would be amazing as many of us are used to naming localizer object simply "_localizer". Regardless of that, tool works fine. Thank you!

**Comment by hishamco** [comment]
Could you please file an issue suggesting that, also you can push a PR if you want to :)
