### ISSUE TITLE
String with \r\n will not get translated properly.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#76]
Example: 

```C#
S["Webhook {0} failed to be added with an exception. \r\n{1}"
```

Result:

```po
#: Aptix.Autodesk\ConstructionCloud\ConstructionCloudCommon\Commands\ProcessWebHooksCommand.cs:150
#. errors.Add(S["Webhook {0} failed to be added with an exception. \r\n{1}", addition.Id, ex.Message]);
msgctxt "Aptix.Autodesk.ConstructionCloud.ConstructionCloudCommon.Commands.ProcessWebHooksCommandHandler"
msgid "Webhook {0} failed to be added with an exception. 
{1}"
msgstr ""
```

Result expected:

```po
#: Aptix.Autodesk\ConstructionCloud\ConstructionCloudCommon\Commands\ProcessWebHooksCommand.cs:150
#. errors.Add(S["Webhook {0} failed to be added with an exception. \r\n{1}", addition.Id, ex.Message]);
msgctxt "Aptix.Autodesk.ConstructionCloud.ConstructionCloudCommon.Commands.ProcessWebHooksCommandHandler"
msgid "Webhook {0} failed to be added with an exception. \r\n{1}"
msgstr ""
```

**Comment by Skrypt** [comment]
This causes a lot of issues later on when we try to automatically translate these string with Google translate as now the string is on 2 different lines. So now it tries to translate 2 different strings.

**Comment by hishamco** [comment]
Please refer me to one of them in OC? I might need to check PO Extractor

**Comment by Skrypt** [comment]
I would simply add a unit test.

**Comment by Skrypt** [comment]
Here it is: 

![image](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/assets/3228637/360e9158-506a-4123-bb93-95fbf5c35172)

**Comment by Skrypt** [comment]
Actually after doing more tests. \r should not be supported by the PoExtrator. It should throw an exception when finding it and warn the user because most tools that I used to parse Po files only supports the usage of \n
