### ISSUE TITLE
Extracting strings from multiple projects

### ISSUE THREAD

**Issue by vukasinpetrovic** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#79]
Hi guys, I started using this tool and it works good and es expected. Thank you for that! I'm writing here as way of asking for help regarding the structure of POT files as I'm confused a bit.

My case is that I have .net web api, that is split into multiple projects. Specifically my API and Application projects have some strings that need translations. 

When I run the poextractor tool, I get POT files for each project (API.pot and Application.pot). And here comes the confusion. When I use PoEdit to add translations, I'm not sure how to combine those two pot files to generate all translations into a single en.po or de.po file. I tried splitting them into separate folder inside Localization folder, but then non of the files are being read as 

`services.AddPortableObjectLocalization(options => options.ResourcesPath = "Localization");` this line only reads from that folder specifically, not subfolders.

So now I'm not sure what is the best thing to do and what is the standard? This is my first time using POT/PO files for translation (I only used resx before), so that's why I need a bit of help. Thank you in advance!

**Comment by hishamco** [comment]
I don't know why you need to combine the translations.

Please have a look at the Orchard Core source, for instance, it contains 200+ projects, so when you need to use the extracted resources in your application just put them in the localization folder

**Comment by hishamco** [comment]
Closed because there's no respond from the author, feel free to reopen
