### ISSUE TITLE
Model with required init property and a source generated type won't resolve namespace and class name

### ISSUE THREAD

**Issue by theo-blis** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#80]
When I clone the repo and run the PoExtractor against the sample folder (see zipfile), it will generate a POT-file with incorrect msgctxt contents for ErrorModel.cs.  The OkModel is the same, but doesn't use required and init property declarations.

Expected:
msgctxt "Sample.ErrorModel"

Actual: 
msgctxt "."

When I debug the code I can see it doesn't resolve namespace and class for the ErrorModel.LegalEntityName property:
![image](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/assets/151923542/8468c256-b1b0-487c-8b1e-90b0fcd22322)

The problem is related to source generation of the property type and the usage of two required and init properties. When I remove one property, I get the namespace.

[out.zip](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/files/14362340/out.zip)
[sample.zip](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/files/14362326/sample.zip)

**Comment by hishamco** [comment]
I did a quick look, the issue comes from the `required` modifier, I will do a fix ASAP

**Comment by theo-blis** [comment]
Thanks, but no rush! I just didn't have the time for a fix, so I wanted to document it as first step.

**Comment by hishamco** [comment]
@theo-blis please check the latest bit and let me know if you have any issue

**Comment by theo-blis** [comment]
@hishamco I ran the modified version against the original source tree and it produces the correct results, without regressions. Thanks for the fix!
