### ISSUE TITLE
Technical debt:  property _ignoredProjects is no longer in use

### ISSUE THREAD

**Issue by theo-blis** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#83]
https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/blob/main/src/OrchardCoreContrib.PoExtractor/Program.cs line 17 is no longer used and can be removed:
![image](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/assets/151923542/30dbcabd-ffde-4520-b538-876fc203c5b9)

IgnoredProject seems to have taken over this responsibility.

**Comment by theo-blis** [comment]
It might be an option to put the default ignored projects in appsettings.json and use IConfigurationBuilder.  The IConfiguration also supports command line arguments, so you could find the settings in the same store.
Notice the challenge when locating the settings file https://github.com/dotnet/sdk/issues/9730.

**Comment by hishamco** [comment]
Don't forget it's a CLI tool, that's why I'm thinking of adding it as option

**Comment by theo-blis** [comment]
Exactly: you could store the default in de appsettings.json and override it via de commandline. When you first add the .AddJsonFile and after that the .AddCommandLine the last one takes priority.
But you are right: too much fuzz to add IConfiguration just for a command line parameter which has a default and which you can override in the future.
