### ISSUE TITLE
Get only one pot file as output.

### ISSUE THREAD

**Issue by VincenzoCarlino** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#93]
Hello, the output of poextractor is a POT template for each project, which can be a bit annoying at times, especially when using POEdit to translate strings. It might be worth considering an option to generate a single POT file as output instead. If this feature is welcomed, I will look into implementing it.

**Comment by hishamco** [comment]
Feel free to submit a PR

**Comment by hishamco** [comment]
> So if you invoke the command with "-s messages.pot" you will get a single file as output.

Don't forget that "messages" could be found in multiple projects

**Comment by VincenzoCarlino** [comment]
> > So if you invoke the command with "-s messages.pot" you will get a single file as output.
> 
> Don't forget that "messages" could be found in multiple projects

What do you mean? By "-s messages.pot", I mean the single output file.
Let me clarify: imagine we have this structure:

- src
   - Project1
   - Project2

If you run "dotnet poextractor ./src ./src", you will find "Project1.pot" and "Project2.pot" in the src directory.
With this feature, if you run "dotnet poextractor ./src ./src --single messages.pot", you will find "messages.pot" in the src directory, containing all the msgIds retrieved from Project1 and Project2.

**Comment by hishamco** [comment]
Got it, the output could be `{culture}.pot`

**Comment by VincenzoCarlino** [comment]
> Got it, the output could be `{culture}.pot`

Why you would specify culture for the pot file?
POT files are the template files for PO files. They will have all the translation strings left empty. A POT file is essentially an empty PO file without the translations, with just the original strings.
So they are "CultureInvariant" :)

**Comment by hishamco** [comment]
Waiting for your PR then we could see
